packages:
  - apps/*
  - packages/*

nodeLinker: hoisted
injectWorkspacePackages: true

allowBuilds:
  browser-tabs-lock: true
  bufferutil: true
  core-js: true
  dtrace-provider: true
  esbuild: true
  protobufjs: true
  unrs-resolver: true
  utf-8-validate: true
